### ISSUE TITLE
wp-theme-boilerplate error

### ISSUE THREAD

**Issue by dashdanilo** [Mill3/mill3-packages#18]
Hi guys, congratulations on the initiative, I found the structures of the projects perfect.

I was trying to implement thema wp-theme-boilerplate to see how it works with barba.js and locomotive scroll with wordpress, but when running the theme on both the docker and localhost it doesn't get past the first step.

Was any file missing? It is a mistake? I couldn't go any further with this to test the boilerplate.

**Comment by thetoine** [comment]
Hi @dashdanilo !

Good, I'm glad the structure fit your needs. Note that this is an internal tool, it's open for anyone on Github but we're not aiming for large audiances.. yet!

Although, there was small bug with package version 0.0.16, upgrade to latest version @0.0.17 and you should be fine for starting dev and build commands.

Did you install the package with NPM, I noticed you forked the repository. The package won't work unless you install it with npm because it's installating a binary for the initial theme install :

https://github.com/Mill3/mill3-packages/blob/master/packages/wp-theme-boilerplate/README.md#how-to-install

If it's still not working, copy-paste the error message below.

Best regards.

**Comment by thetoine** [comment]
Also note that our boilerplate is using our utility class framework.

Documentation site here : [mill3-system-ui-sass-demo-site.netlify.app]( https://mill3-system-ui-sass-demo-site.netlify.app/) (although this is still very much a WIP with undocumented features)

**Comment by dashdanilo** [comment]
I tried again, but not after I choose the path to install thema it does not proceed to the next step
